export const ACTIONS = {
    QUESTION_SELECT_ANSWER: 'QUESTION_SELECT_ANSWER',
    QUIZ_SUBMIT: 'QUIZ_SUBMIT',
    NAVIGATION_QUESTIONS_LIST: 'NAVIGATION_QUESTIONS_LIST',
};

export const SCREENS = {
    QUESTIONS_LIST: 'QuestionsList',
    RESULTS_LIST: 'ResultsList'
};
